### ISSUE TITLE
Set Consul host/port via environment variables

### ISSUE THREAD

**Issue by risbarov** [rabbitmq/rabbitmq-peer-discovery-consul#11]
Hello!

Is there a way to set Consul host/port via environment variables instead of using cluster_formation.consul.host / cluster_formation.consul.port in configuration file?

Thanks!

**Comment by michaelklishin** [comment]
[There is](https://github.com/rabbitmq/rabbitmq-peer-discovery-consul/blob/master/include/rabbit_peer_discovery_consul.hrl#L25) but it's a rudiment inherited from rabbitmq-autocluster. Using configuration file is superior in many ways (e.g. value validation), that's why that's the only documented option.
