### ISSUE TITLE
only_log_warning fails to set on 3.7.7 & 3.7.8 in new config style format

### ISSUE THREAD

**Issue by NamelessHH** [rabbitmq/rabbitmq-peer-discovery-consul#21]
we're trying to set cluster_formation.node_cleanup.only_log_warning to false in the new stype format in the config file and we're getting an error

`Config file generation failed {ipaddress} [error] You've tried to set cluster_formation.node_cleanup.only_log_warning, but there is no setting with that name.`

our exact line's are

`cluster_formation.peer_discovery_backend = rabbit_peer_discovery_dns`
`cluster_formation.dns.hostname = {DNS Name}`
`cluster_formation.node_cleanup.only_log_warning = false`

**Comment by NamelessHH** [comment]
we tried changing it and we're also getting 

`Config file generation failed 20:02:59.762 [error] You've tried to set cluster_formation.aws.region, but there is no setting with that name.`

with config
`cluster_formation.peer_discovery_backend = rabbit_peer_discovery_aws`
`cluster_formation.aws.region = us-east-1`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm not sure what either DNS or AWS-based peer discovery has to do with Consul.

The setting [is there](https://github.com/rabbitmq/rabbitmq-peer-discovery-common/blob/master/priv/schema/rabbitmq_peer_discovery_common.schema).

Almost certainly you haven't enabled any peer discovery plugins, which in turn means `rabbitmq-peer-discovery-common` is not enabled and its config schema is not considered by the broker.

This is mailing list material.

**Comment by michaelklishin** [comment]
We updated the [Cluster Formation guide](http://www.rabbitmq.com/cluster-formation.html) to clarify that some settings come from plugins and plugins must be enabled before node startup.

**Comment by NamelessHH** [comment]
Thanks it seems that we just weren't clear that using DNS peer discover we still had to enable the rabbitmq-peer-discovery-common rabbit plugin to use the only_log_warning  setting.

**Comment by michaelklishin** [comment]
@NamelessHH if you think that the current docs do still emphasize that enough I can take another pass at them. Let us know.
