### ISSUE TITLE
Autocluster using Consul backend fails to update it's own cluster state when shutting down

### ISSUE THREAD

**Issue by heanssgen-troy** [rabbitmq/rabbitmq-peer-discovery-consul#23]
RabbitMQ nodes using autocluster and the consul service backend fail to properly shut down when asked to using the 'rabbitmqctl shutdown' (https://www.rabbitmq.com/rabbitmqctl.8.html) command. Specifically, all nodes **except** the one being shut down are properly updated, while the node being shut down still believes that it is part of the cluster.

```
rbt-1:
2018-12-03 16:55:57.277 [info] <0.42.0> Application rabbitmq_peer_discovery_consul exited with reason: stopped
2018-12-03 16:55:57.277 [info] <0.1326.0> Stopping application 'rabbitmq_peer_discovery_common'
2018-12-03 16:55:57.277 [info] <0.42.0> Application rabbitmq_peer_discovery_common exited with reason: stopped
2018-12-03 16:55:57.277 [info] <0.1326.0> Stopping application 'rabbitmq_management_agent'
2018-12-03 16:55:57.279 [info] <0.42.0> Application rabbitmq_management_agent exited with reason: stopped
2018-12-03 16:55:57.279 [info] <0.1326.0> Stopping application 'rabbit'
2018-12-03 16:55:57.279 [info] <0.211.0> Will unregister with peer discovery backend rabbit_peer_discovery_consul
2018-12-03 16:55:57.300 [info] <0.211.0> Consul's response to the unregistration attempt: []

insite@ISC8:~/rabbit@gb3.node.evertz$ cat cluster_nodes.config 
{['rabbit@gb2.node.evertz','rabbit@gb3.node.evertz'],['rabbit@gb2.node.evertz','rabbit@gb3.node.evertz']}.
```

Its cluster partner, rbt-2 looks like this.

```
rbt-2:
insite@insite-w-c1:~/rabbit@gb2.node.evertz$ cat cluster_nodes.config 
{['rabbit@gb2.node.evertz'],['rabbit@gb2.node.evertz']}.
```

Attempting to restart a node that has gracefully left this way will result in:

```
Error description:
    init:do_boot/3
    init:start_em/1
    rabbit:start_it/1 line 450
    rabbit:'-boot/0-fun-0-'/0 line 305
    rabbit_mnesia:check_cluster_consistency/0 line 664
throw:{error,{inconsistent_cluster,"Node 'rabbit@gb3.node.evertz' thinks it's clustered with node 'rabbit@gb2.node.evertz', but 'rabbit@gb2.node.evertz' disagrees"}}
Log file(s) (may contain more information):
```

This is inconsistent with the behavior described by (http://www.rabbitmq.com/cluster-formation.html#rejoining). Expected behavior would be that the node would simply shut down (leaving the cluster state intact with 1 fewer nodes), properly rejoining when `rabbitmq-server -detached start` is run again.

A proper fix consistent with the documentation is to not modify cluster state when a node shutdown is issued. This way, nodes shutting down and coming back up will not force the operator to run a 'reset' command on the node before starting the service.

**Comment by michaelklishin** [comment]
The message clearly suggests that either the node was removed from the cluster or it (or its peers) was started with a different node data directory (and therefore is a blank node).

Such scenarios are commonly brought up on the mailing list in the context of Kubernetes where due to incorrect user expectations or node data directory location.

This plugin has absolutely no effect on the node rejoining behavior because peer discovery is not performed upon rejoining (as the docs clearly state).

Server logs should provide a lot of relevant information. This is mailing list material.

**Comment by michaelklishin** [comment]
Here's the [most famous thread](https://groups.google.com/d/msg/rabbitmq-users/wuOfzEywHXo/WUZjBbqlCwAJ) with a similar problem which ended up being an effect from [opt-in unknown node removal](http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup) which the user has enabled without realizing the consequences.

My reading of the original post suggests that @heanssgen-troy believes that `rabbitmqctl shutdown` removes the node from the cluster. That's not the case, only `rabbitmqctl forget_cluster_nodes` or [opt-in cleanup of unknown nodes](http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup) does. Except for node resets and manual deletion of node's data directory, under no other circumstance a node is removed from its current cluster.

**Comment by heanssgen-troy** [comment]
I believe there is a slight misunderstanding of what I am reporting. I will attempt to clarify. There are a few differences between the two states.

I do not believe that `rabbitmqctl shutdown` should remove the node from the cluster. This is what I am reporting (perhaps in the wrong subsystem). A shutdown of the node and then **immediate** restart of the node (with an absurdly long cleanup time, upwards of a day) leaves the cluster in an inconsistent state.

The relevant part of the init script is provided below

```
    os.environ['RABBITMQ_NODENAME'] = 'rabbit@%s.node.evertz' % node
    os.environ['RABBITMQ_USE_LONGNAME'] = 'true'

    nature_home = environment['application']['nature-home']
    erlang = os.path.join(nature_home, 'dependencies', 'erlang', 'lib', 'erlang')
    rabbitmq = os.path.join(nature_home, 'dependencies', 'rabbitmq', 'sbin', 'rabbitmqctl')
    user = environment['application']['nature']['user']

    try:
        logging.info("Stopping rabbitmq application")
        check_process = subprocess.Popen(shlex.split('%s shutdown' % rabbitmq))
        check_process.wait()
    except Exception as e:
        logging.info(str(e))

    logging.info("Giving rabbit a few seconds to write its database")
    time.sleep(5)
```

This is what produces the outcome I have described above. The moment the rabbitmqctl shutdown command is issued, all _other_ nodes in the system immediately remove this node from their cluster_nodes.config file, while the node being shutdown is not updated appropriately.

At no point is the data directory moved or deleted, nor is the `rabbitmqctl forget_cluster_node` command issued. If it was, I would tend to agree with you on this matter.

**Comment by michaelklishin** [comment]
@heanssgen-troy that file reflects the list of known online peers (at the moment or at the time of shutdown). Whether the node being shut down removes itself from that list doesn't really matter since a node will always consider itself to be a member of its cluster. That list is also different from the list
of known cluster peers used in other contexts (most notably, schema data store cluster members).
This plugin has absolutely no effect on that.

The message you provided (`"Node 'rabbit@gb3.node.evertz' thinks it's clustered with node 'rabbit@gb2.node.evertz', but 'rabbit@gb2.node.evertz' disagrees"`) is unambiguous: between node shutdown and restart, *something* has changed about cluster membership of those two nodes. See the Kubernetes thread above for an example. Or try this:

 * Set up a cluster of 2 nodes, A and B
 * Shut down A
 * Reset B
 * Restart B
 * Restart A

A will assume that B is its peer it can sync from but B has since been reset and its schema database cluster identification is now completely different, so it will refuse a clustering request from A.

Something causes that effect in your environment. I don't know what it is since you haven't posted
any logs or steps taken and I don't know what the intent of your deployment tool or init script is.

This is 100% mailing list material.

**Comment by heanssgen-troy** [comment]
@michaelklishin Fair enough. I have posted this to the mailing list on the chance that I am doing something arcane, however I wished to clarify for any other users coming here what I was seeing and what was expected.

My steps are as follows (for anyone who comes here later):

```
node-1$:
systemctl start rabbitmq

node-2$:
systemctl start rabbitmq
sleep 5
systemctl stop rabbitmq
sleep 2
systemctl start rabbitmq
```

For the record, I agree with you on every count. What I am seeing and what I am getting are two completely different things. 

Thank you for your time :)

**Comment by michaelklishin** [comment]
I updated the docs to describe the error message above and what might lead a node to fail to rejoin its peers.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/d/msg/rabbitmq-users/Az8c884dae8/uPqfYZG_BAAJ). TL;DR: the user had forced node cleanup enabled, just like in the Kubernetes thread mentioned above.
