### ISSUE TITLE
Service DNS resolution

### ISSUE THREAD

**Issue by korporationcl** [rabbitmq/rabbitmq-peer-discovery-consul#25]
Hello there, I have been trying to find a figure out how the following behaviour. I'm currently bootstrapping my cluster with the following settings:

```
..
    {cluster_formation,   [
    {peer_discovery_backend, rabbit_peer_discovery_consul},
    {peer_discovery_consul, [
      {consul_host, localhost},{consul_port, 8500},{consul_svc, rabbitmq},{consul_svc_addr_auto, true},{consul_svc_addr_use_nodename, false}
    ]}
  ]
},
...
```

Cluster is formed and nodes are discovered properly, but when I try to resolve the service with `dig`, for example, I can only get the CNAME records for the nodes:

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> rabbitmq.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61561
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;rabbitmq.service.consul.	IN	A

;; ANSWER SECTION:
rabbitmq.service.consul. 0	IN	CNAME	ip-10-83-10-36.
rabbitmq.service.consul. 0	IN	CNAME	ip-10-83-6-222.

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jan 16 04:23:26 UTC 2019
;; MSG SIZE  rcvd: 108
```

even using +recursion with dig doesn't get the results that I would expect, so I was wondering how can I make sure that the address of the service (rabbitmq.service.consul) will be resolvable in a transparent way for the user and application (get a CNAME plus A records, or A records only without affecting the cluster formation during bootstrap since we need to use a DNS name and not an IP Address).

I'm not sure if this will help but we deploy our clusters using Puppet and use RabbitMQ 3.7.7.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin or RabbitMQ do not control how hostname resolution is performed. Use whatever means you find convenient. The plugin does have a way for you to [specify what hostname suffix](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-consul) is used and how it is computed.

Erlang has a mechanism, called [inetrc](http://erlang.org/doc/apps/erts/inet_cfg.html), which can configure hostname resolution specifically for Erlang VMs when OS-level controls are not available or practical. It was covered multiple time on the mailing list, most recently [in this thread](https://groups.google.com/d/msg/rabbitmq-users/QYrtYmGZavg/JGX6gv2WDwAJ). In most cases, you don't need to use inetrc, although we don't discourage its use.

**Comment by korporationcl** [comment]
> This plugin or RabbitMQ do not control how hostname resolution is performed. Use whatever means you find convenient. The plugin does have a way for you to [specify what hostname suffix](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-consul) is used and how it is computed.
> 
> Erlang has a mechanism, called [inetrc](http://erlang.org/doc/apps/erts/inet_cfg.html), which can configure hostname resolution specifically for Erlang VMs when OS-level controls are not available or practical. It was covered multiple time on the mailing list, most recently [in this thread](https://groups.google.com/d/msg/rabbitmq-users/QYrtYmGZavg/JGX6gv2WDwAJ). In most cases, you don't need to use inetrc, although we don't discourage its use.

Thanks for the reference, sorry about the inconvenience

**Comment by AndreLobato** [comment]
Just some additional information for whoever hit this issue and ends up here, that's how I solved...

I had to create a `rabbitmq-env.conf` with, which sets the node name as rabbit@[IP address]:
```
NODENAME=rabbit@`python -c "import socket;print socket.gethostbyname(socket.gethostname())"`
USE_LONGNAME=true
NODE_TYPE=-name
ERLANG_COOKIE=anycookiehere
```
**Note:** I've used Python to get the IP address because it's what's available on the official RabbitMQ Docker image, but not the `ip` command. You may choose to use another method to get the IP from the correct network interface.

Then on the `rabbitmq.conf` added this plugin configs telling to use the network interface as the reference for the service...

```
cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_consul
cluster_formation.consul.host = consul (here add the relevant consul hostname)
cluster_formation.consul.svc = rabbitmq
cluster_formation.consul.svc_addr_auto = true
cluster_formation.consul.svc_addr_use_nodename = false
cluster_formation.consul.svc_addr_nic = eth0
... all the other rabbitmq configs
```

And placed those files in `/etc/rabbitmq/` (default location) as well the `enabled_plugins` file as the example in this repo with:

```
[rabbitmq_management,rabbitmq_peer_discovery_consul].
```

As described in this repo examples folder. After that I could successfuly resolve `rabbitmq.service.consul` to the containers ip addresses.

I hope it helps.

**Comment by AndreLobato** [comment]
If by "out of the box" you mean the official version of RabbitMQ Docker image, yes. No further settings or commands were required to each node to join the cluster on start.

**Comment by michaelklishin** [comment]
Thanks for the example. As long as

 * The plugin is [preconfigured to be enabled](http://www.rabbitmq.com/plugins.html#enabled-plugins-file) (or enabled any other way)
 * Nodes [compute/communicate their hostnames](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-consul) such that other nodes can resolve them
 * [Nodes can authenticate](http://www.rabbitmq.com/clustering.html#erlang-cookie) to each other
 * All nodes connect to the same Consul cluster and can read and write to it

then peer discovery should succeed regardless of whether Docker is used, what image is used,
and so on. Those 4 things are key.

This is not a discussion forum, though => closing.
