### ISSUE TITLE
Consul service removed when cluster node count goes below 2

### ISSUE THREAD

**Issue by domgoodwin** [rabbitmq/rabbitmq-peer-discovery-consul#26]
'rabbitmq' service is removed from consul when the rabbitmq server on 1/2 nodes is stopped, restarting the rabbitmq server on the remaining standalone node restores it.

To replicate:
- Have two rabbitmq nodes setup to cluster via consul
- Check consul for the 'rabbitmq' service
- Stop rabbitmq server on one node
- 'rabbitmq' service has gone from consul
- Restarting the still running service on the remaining box and it returns

Versions:
RabbitMQ 3.7.4

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
