### ISSUE TITLE
How do you configure cluster_formation.consul.svc_addr_nic = en0 on Windows

### ISSUE THREAD

**Issue by danassetms** [rabbitmq/rabbitmq-peer-discovery-consul#45]
Following the guidance to setup a Consul RabbitMQ cluster I've get everything working except this.  My service registers with the node name which can't then be resolved by anything else using Consul so I need RabbitMQ to register with the IP address of the machine but I can't get this option to work:

cluster_formation.consul.svc_addr_nic = en0

It just causes Rabbit to crash with the following error

2020-06-03 19:36:20.124 [info] <0.345.0> Will register with peer discovery backend rabbit_peer_discovery_consul
2020-06-03 19:36:20.124 [error] <0.344.0> CRASH REPORT Process <0.344.0> with 0 neighbours exited with reason: no match of right hand value {error,not_found} in rabbit_peer_discovery_consul:service_address/4 line 415 in application_master:init/4 line 138
2020-06-03 19:36:20.124 [info] <0.44.0> Application rabbit exited with reason: no match of right hand value {error,not_found} in rabbit_peer_discovery_consul:service_address/4 line 415

**Comment by danassetms** [comment]
Full config that I'm having to use to get it working:

cluster_formation.peer_discovery_backend = rabbit_peer_discovery_consul
cluster_formation.consul.host = xxxxx
cluster_formation.consul.port = xxxxx
cluster_formation.consul.svc = rabbitmq
cluster_formation.consul.acl_token = b9e2bfcc-8d0e-7f6a-5a0d-663741a8e834
cluster_formation.consul.svc_port = 5675
cluster_formation.consul.svc_addr_auto = false
cluster_formation.consul.svc_addr_use_nodename = false
cluster_formation.consul.svc_addr = 10.0.0.4

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
